"""File discovery with layered ignore semantics and symlink safety.

Ignore precedence, lowest to highest:
1. default exclusions (.git, .poldergraph, node_modules, build output, venvs)
2. configured include/exclude globs
3. .gitignore (including nested rules)
4. .ignore
5. .poldergraphignore
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath
from typing import Any

from pathspec import PathSpec
from pathspec.patterns import GitWildMatchPattern

from .languages import is_document_path, is_media_path, language_for_path

INDEX_DIR_NAME = ".poldergraph"

#: Directories excluded by default: VCS metadata, caches, build output and
#: package caches that would otherwise dominate the graph with vendored code.
DEFAULT_EXCLUDED_DIRS: frozenset[str] = frozenset(
    {
        ".git",
        ".hg",
        ".svn",
        INDEX_DIR_NAME,
        "node_modules",
        "bower_components",
        "vendor",
        "venv",
        ".venv",
        "virtualenv",
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".tox",
        ".nox",
        ".cache",
        "dist",
        "build",
        "out",
        "output",
        "target",
        "coverage",
        ".next",
        ".nuxt",
        ".svelte-kit",
        ".gradle",
        ".idea",
        ".vscode-test",
        "site-packages",
        ".eggs",
        ".terraform",
        "Pods",
        "DerivedData",
        "obj",
        "bin",
        ".dart_tool",
        "obj",
    }
)

#: Suffixes of minified/bundled output that should never be parsed as source.
MINIFIED_SUFFIXES: tuple[str, ...] = (".min.js", ".min.css", ".bundle.js", ".min.mjs")

#: Header markers that identify machine-generated source files.
GENERATED_HEADER_MARKERS: tuple[str, ...] = (
    "@generated",
    "code generated by",
    "do not edit",
    "do not modify",
    "autogenerated",
    "auto-generated",
    "automatically generated",
    "this file was automatically generated",
    "generated by the protocol buffer compiler",
    "@generated by",
)

#: Path fragments that conventionally mark generated or vendored trees.
GENERATED_PATH_MARKERS: tuple[str, ...] = (
    ".pb.go",
    "_pb2.py",
    ".generated.",
    ".g.dart",
    ".freezed.dart",
    "_generated.py",
    "/generated/",
    "/__generated__/",
    "/autogen/",
    ".min.",
    "/migrations/",
)


def _mtime_ns(stat_result: os.stat_result) -> int:
    """Nanosecond mtime, portable across platforms that only expose seconds."""
    seconds = int(stat_result.st_mtime)
    nsec = getattr(stat_result, "st_mtime_ns", None)
    if nsec is not None:
        return int(nsec)
    return seconds * 1_000_000_000


@dataclass
class DiscoveredFile:
    """One file selected for indexing."""

    path: str
    """Root-relative POSIX path."""
    abs_path: Path
    size: int
    mtime_ns: int
    language: str | None = None
    is_generated: bool = False
    is_media: bool = False
    is_document: bool = False
    kind_hint: str = "source"
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class DiscoveryResult:
    files: list[DiscoveredFile]
    skipped_dirs: int = 0
    ignored_count: int = 0
    total_seen: int = 0

    @property
    def by_language(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for f in self.files:
            key = f.language or "unknown"
            counts[key] = counts.get(key, 0) + 1
        return counts


def root_id_for(path: Path) -> str:
    """Stable root identity derived from the resolved absolute path."""
    import hashlib

    resolved = str(path.resolve())
    return "root:" + hashlib.sha256(resolved.encode("utf-8")).hexdigest()[:16]


def detect_root(start: Path | None = None) -> Path:
    """Find the workspace root.

    Prefers a Git root, then a directory containing project markers, then the
    starting directory itself. Works outside Git repositories.
    """
    current = (start or Path.cwd()).resolve()
    if current.is_file():
        current = current.parent

    markers = (
        ".git",
        "pyproject.toml",
        "package.json",
        "Cargo.toml",
        "go.mod",
        "pom.xml",
        "build.gradle",
        "build.gradle.kts",
        "Gemfile",
        "composer.json",
        "CMakeLists.txt",
        ".poldergraph",
    )
    for directory in [current, *current.parents]:
        for marker in markers:
            if (directory / marker).exists():
                return directory
    return current


def detect_git_roots(start: Path) -> list[Path]:
    """Detect nested repository roots for multi-root workspaces."""
    roots: list[Path] = []
    base = start.resolve()
    skip_dirs = {INDEX_DIR_NAME, "node_modules", ".git"}
    for dirpath, dirnames, _ in os.walk(base):
        dirnames[:] = [d for d in dirnames if d not in skip_dirs]
        current = Path(dirpath)
        if (current / ".git").exists():
            roots.append(current)
    return sorted(roots)


def _load_spec(root: Path, filename: str) -> PathSpec | None:
    path = root / filename
    if not path.is_file():
        return None
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return None
    patterns = []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        patterns.append(stripped)
    if not patterns:
        return None
    return PathSpec.from_lines(GitWildMatchPattern, patterns)


def read_gitignore_spec(root: Path) -> PathSpec | None:
    return _load_spec(root, ".gitignore")


def read_ignore_spec(root: Path) -> PathSpec | None:
    return _load_spec(root, ".ignore")


def read_poldergraphignore_spec(root: Path) -> PathSpec | None:
    return _load_spec(root, ".poldergraphignore")


def is_generated_file(relative_path: str, head_text: str = "") -> bool:
    """Detect generated code from path conventions and file headers."""
    lowered = relative_path.lower()
    if any(lowered.endswith(suffix) for suffix in MINIFIED_SUFFIXES):
        return True
    if any(marker in lowered for marker in GENERATED_PATH_MARKERS):
        return True
    head = head_text[:2000].lower()
    return any(marker in head for marker in GENERATED_HEADER_MARKERS)


def is_safe_path(root: Path, candidate: Path) -> bool:
    """Reject symlink escapes and traversal outside the root."""
    try:
        resolved_root = root.resolve()
        resolved = candidate.resolve()
    except (OSError, RuntimeError):
        return False
    try:
        resolved.relative_to(resolved_root)
    except ValueError:
        return False
    return True


class Discovery:
    """Walk a root and select indexable files."""

    def __init__(
        self,
        root: Path,
        *,
        include: list[str] | None = None,
        exclude: list[str] | None = None,
        follow_symlinks: bool = False,
        include_generated: bool = False,
        include_media: bool = True,
        max_file_bytes: int = 5_000_000,
        max_roots: int = 64,
    ) -> None:
        self.root = root.resolve()
        self.follow_symlinks = follow_symlinks
        self.include_generated = include_generated
        self.include_media = include_media
        self.max_file_bytes = max_file_bytes
        self.max_roots = max_roots
        self.include_spec = PathSpec.from_lines(GitWildMatchPattern, include) if include else None
        self.exclude_spec = PathSpec.from_lines(GitWildMatchPattern, exclude) if exclude else None
        self.gitignore = read_gitignore_spec(self.root)
        self.ignore_spec = read_ignore_spec(self.root)
        self.pgignore = read_poldergraphignore_spec(self.root)

    def is_ignored(
        self,
        relative_path: str,
        is_dir: bool,
        nested_specs: list[tuple[str, PathSpec]],
    ) -> bool:
        """Apply ignore layers in documented precedence order.

        ``nested_specs`` carries (prefix, spec) pairs for every .gitignore found
        below the root; each is matched against the path relative to the
        directory that declared it, as git does.
        """
        candidate = relative_path + "/" if is_dir else relative_path
        if self.include_spec and not is_dir and not self.include_spec.match_file(relative_path):
            return True
        if self.exclude_spec and self.exclude_spec.match_file(candidate):
            return True
        if self.gitignore and self.gitignore.match_file(candidate):
            return True
        for prefix, spec in nested_specs:
            if relative_path.startswith(prefix):
                local = relative_path[len(prefix):]
                if spec.match_file(local + "/" if is_dir else local):
                    return True
        if self.ignore_spec and self.ignore_spec.match_file(candidate):
            return True
        if self.pgignore and self.pgignore.match_file(candidate):
            return True
        return False

    def scan(self) -> DiscoveryResult:
        result = DiscoveryResult(files=[])
        self._walk(self.root, "", result, [])
        result.files.sort(key=lambda f: f.path)
        return result

    def _nested_spec(self, directory: Path, prefix: str) -> list[tuple[str, PathSpec]]:
        """Load .gitignore files declared inside ``directory``."""
        specs: list[tuple[str, PathSpec]] = []
        for name in (".gitignore", ".ignore"):
            path = directory / name
            if not path.is_file():
                continue
            try:
                lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
            except OSError:
                continue
            patterns = [line.strip() for line in lines if line.strip() and not line.strip().startswith("#")]
            if patterns:
                specs.append((prefix, PathSpec.from_lines(GitWildMatchPattern, patterns)))
        return specs

    def _walk(
        self,
        directory: Path,
        prefix: str,
        result: DiscoveryResult,
        inherited: list[tuple[str, PathSpec]],
    ) -> None:
        if len(result.files) > 200_000:  # runaway guard for pathological trees
            return
        try:
            entries = sorted(os.scandir(directory), key=lambda e: e.name)
        except (OSError, PermissionError):
            return

        nested_specs = [*inherited, *self._nested_spec(directory, prefix)]

        for entry in entries:
            name = entry.name
            rel = f"{prefix}{name}"
            try:
                is_symlink = entry.is_symlink()
            except OSError:
                continue

            if is_symlink and not self.follow_symlinks:
                continue

            abs_path = Path(entry.path)
            if is_symlink and not is_safe_path(self.root, abs_path):
                continue

            try:
                is_dir = entry.is_dir(follow_symlinks=self.follow_symlinks)
            except OSError:
                continue

            if is_dir:
                if name in DEFAULT_EXCLUDED_DIRS:
                    result.skipped_dirs += 1
                    continue
                if self.is_ignored(rel, True, nested_specs):
                    result.ignored_count += 1
                    continue
                self._walk(abs_path, f"{rel}/", result, nested_specs)
                continue

            result.total_seen += 1
            if self.is_ignored(rel, False, nested_specs):
                result.ignored_count += 1
                continue

            try:
                stat_result = entry.stat(follow_symlinks=self.follow_symlinks)
            except OSError:
                continue

            if stat_result.st_size > self.max_file_bytes:
                continue

            head = ""
            if stat_result.st_size <= 65536:
                try:
                    with open(abs_path, "rb") as handle:
                        head = handle.read(2048).decode("utf-8", errors="replace")
                except OSError:
                    continue

            generated = is_generated_file(rel, head)
            if generated and not self.include_generated:
                continue

            language = language_for_path(rel)
            media = is_media_path(rel)
            document = is_document_path(rel)
            if media and not self.include_media:
                continue
            if language is None and not media:
                continue

            kind_hint = "source"
            if media:
                kind_hint = "media"
            elif document:
                kind_hint = "document"

            result.files.append(
                DiscoveredFile(
                    path=rel,
                    abs_path=abs_path,
                    size=stat_result.st_size,
                    mtime_ns=_mtime_ns(stat_result),
                    language=language,
                    is_generated=generated,
                    is_media=media,
                    is_document=document,
                    kind_hint=kind_hint,
                )
            )


def safe_join(root: Path, relative: str) -> Path | None:
    """Resolve a repository-relative path, refusing traversal and symlink escapes.

    This is the single guard used by every filesystem access outside discovery,
    including the dashboard's source endpoint.
    """
    if not relative or "\x00" in relative:
        return None
    normalized = relative.replace("\\", "/").strip()
    if normalized.startswith("/"):
        return None
    parts = [p for p in PurePosixPath(normalized).parts if p not in (".",)]
    if any(part == ".." for part in parts):
        return None
    candidate = root.joinpath(*parts)
    if not is_safe_path(root, candidate):
        return None
    return candidate